query SearchJobs($input: SearchJobsInput!) {
  searchJobs(input: $input) {
    id
    title
    location
    type
    remote
    salary
    company {
      id
      name
    }
    createdAt
    isApplied
    officeAddress {
      ... on UKAddress {
        addressLine1
        addressLine2
        city
        postcode
      }
      ... on USAddress {
        street
        city
        state
        zip
      }
    }
  }
}

mutation ApplyForJob($input: ApplyForJobInput!) {
  applyForJob(input: $input)
}
